### ISSUE TITLE
进程一章的进程间通信一节，第一段“容器”应当为“容易”

### ISSUE THREAD

**Issue by danfate** [ethan-funny/explore-python#8]
另外，教程写的很简明，就是进程、线程和协程这边开始对我这样的小白就有一些吃力了。不过每一章的总结都很棒！

**Comment by ethan-funny** [comment]
好的，谢谢指正。

**Comment by danfate** [comment]
Hi,
在Requests库的使用这一章，重定向这一节的例子在python2.7下会报错，猜测是不是因为Https证书问题？
```
>>> import requests
>>> headers={'User-Agent':'Mozilla/4.0(compatible;MSIE 5.5;Windows NT)'}
>>> r=requests.get('https://toutiao.io/shares/789751/url',headers=headers)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(53, 'Software caused connection abort'))
```

**Comment by ethan-funny** [comment]
Hi, 测了一下，应该是要访问的链接重定向的网站 https 证书的问题，你可以试试访问 https://toutiao.io/k/c32y51 。
